export { PrismaClient } from "@prisma/client";
export type {
  Category,
  CategoryTranslation,
  Country,
  Currency,
  CurrencyExchangeRate,
  GovernanceActionCategory,
  GovernanceActionReview,
  GovernanceApprovalStatus,
  GovernanceRiskLevel,
  Invoice,
  Language,
  Locale,
  PaymentGatewayConfiguration,
  PaymentGatewayProvider,
  PaymentGatewayStatus,
  Plan,
  Prisma,
  Product,
  ProductImage,
  ProductTranslation,
  ProductVariant,
  ProductVariantPrice,
  Role,
  Shop,
  ShopStaff,
  ShopTranslation,
  ShippingZone,
  ShippingZoneCountry,
  ShippingZoneStatus,
  Subscription,
  TaxProfile,
  TaxProfileStatus,
  User,
  UserRole,
} from "@prisma/client";
